services:
  - type: web
    name: n8n
    env: docker
    plan: free
    region: oregon
    disk:
      name: n8n-data
      mountPath: /home/node/.n8n
      sizeGB: 1
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: muhammadabdullah
      - key: N8N_BASIC_AUTH_PASSWORD
        value: flower\182
      - key: WEBHOOK_URL
        value: https://example.com
